# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropboxFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=4096)),
                ('server_modified', models.DateTimeField()),
                ('size', models.BigIntegerField()),
                ('name', models.CharField(max_length=4096)),
                ('path_lower', models.CharField(max_length=4096)),
                ('path_display', models.CharField(max_length=4096)),
            ],
        ),
    ]
