from models import Schema
from helpers import *

js_group_dress = Schema({
    "Style Number": (int, int),
    "Dress Name": (str, str),
    "Dress Description": (str, str),
    "Collection": (str, str),
    "Sizes": (list_int, lambda x: ','.join(str(y) for y in x)),
    "Colors": (list_split_strip, lambda x: ','.join(x)),
    "Price (USD)": (int_from_string, int)
})
shopify_product = Schema({
    "Handle": (str, str),
    "Title": (str, str),
    "Body (HTML)": (str, str),
    "Vendor": (str, str),
    "Type": (str, str),
    "Tags": (list_split_strip, None),
    "Published": (bool_from_str_blank_true, None),
    "Option1 Name": (str, str),
    "Option1 Value": (str, str),
    "Option2 Name": (str, str),
    "Option2 Value": (str, str),
    "Option3 Name": (str, str),
    "Option3 Value": (str, str),
    "Variant SKU": (str, str),
    "Variant Grams": (int, int),
    "Variant Inventory Tracker": (str, str),
    "Variant Inventory Qty": (int, int),
    "Variant Inventory Policy": (str, str),
    "Variant Fulfillment Service": (str, str),
    "Variant Price": (two_place_float_from_str, None),
    "Variant Compare At Price": (two_place_float_from_str, None),
    "Variant Requires Shipping": (bool_from_str, None),
    "Variant Taxable": (bool_from_str, None),
    "Variant Barcode": (str, str),
    "Image Src": (str, str),
    "Image Alt Text": (str, str),
    "Gift Card": (None, None),
    "SEO Title": (str, str),
    "SEO Description": (str, str),
    "Google Shopping / MPN": (None, None),
    "Google Shopping / Age Group": (None, None),
    "Google Shopping / Gender": (None, None),
    "Google Shopping / Google Product Category": (None, None),
    "Google Shopping / AdWords Grouping": (None, None),
    "Google Shopping / AdWords Labels": (None, None),
    "Google Shopping / Condition": (None, None),
    "Google Shopping / Custom Product": (None, None),
    "Google Shopping / Custom Label 0": (None, None),
    "Google Shopping / Custom Label 1": (None, None),
    "Google Shopping / Custom Label 2": (None, None),
    "Google Shopping / Custom Label 3": (None, None),
    "Google Shopping / Custom Label 4": (None, None),
    "Variant Image": (str, str),
    "Variant Weight Unit": (None, None)
})
