import collections
from models import Schema
from helpers import *

js_group_dress = Schema(collections.OrderedDict([
    ("Style Number", (int, int)),
    ("Dress Name", (str, str)),
    ("Dress Description", (str, str)),
    ("Collection", (str, str)),
    ("Presell", (bool_from_str, str_from_bool)),
    ("Sizes", (list_of_int_from_str, str_from_list)),
    ("Colors", (list_split_strip, str_from_list)),
    ("Price (USD)", (int_from_string, int))
]))

shopify_product = Schema(collections.OrderedDict([
    ("Handle", (str, str)),
    ("Title", (str, str)),
    ("Body (HTML)", (str, str)),
    ("Vendor", (str, str)),
    ("Type", (str, str)),
    ("Tags", (list_split_strip, str_from_list)),
    ("Collection", (str, str)),
    ("Published", (bool_from_str_blank_true, str_from_bool)),
    ("Image Src", (str, str)),
    ("Image Alt Text", (str, str)),
    ("SEO Title", (str, str)),
    ("SEO Description", (str, str)),
    ("Option1 Name", (str, str)),
    ("Option1 Value", (str, str)),
    ("Option2 Name", (str, str)),
    ("Option2 Value", (str, str)),
    ("Option3 Name", (str, str)),
    ("Option3 Value", (str, str)),
    ("Variant SKU", (str, str)),
    ("Variant Grams", (int, int)),
    ("Variant Inventory Tracker", (str, str)),
    ("Variant Inventory Qty", (int, int)),
    ("Variant Inventory Policy", (str, str)),
    ("Variant Fulfillment Service", (str, str)),
    ("Variant Price", (two_place_float_from_str, None)),
    ("Variant Compare At Price", (two_place_float_from_str, None)),
    ("Variant Requires Shipping", (bool_from_str, str_from_bool)),
    ("Variant Taxable", (bool_from_str, str_from_bool)),
    ("Variant Barcode", (str, str)),
    ("Variant Image", (str, str)),
    ("Variant Weight Unit", (None, None)),
    ("Gift Card", (None, None)),
    ("Google Shopping / MPN", (None, None)),
    ("Google Shopping / Age Group", (None, None)),
    ("Google Shopping / Gender", (None, None)),
    ("Google Shopping / Google Product Category", (None, None)),
    ("Google Shopping / AdWords Grouping", (None, None)),
    ("Google Shopping / AdWords Labels", (None, None)),
    ("Google Shopping / Condition", (None, None)),
    ("Google Shopping / Custom Product", (None, None)),
    ("Google Shopping / Custom Label 0", (None, None)),
    ("Google Shopping / Custom Label 1", (None, None)),
    ("Google Shopping / Custom Label 2", (None, None)),
    ("Google Shopping / Custom Label 3", (None, None)),
    ("Google Shopping / Custom Label 4", (None, None))
]))
